# Generated by Django 2.0.3 on 2018-03-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mill', models.CharField(max_length=50)),
                ('vendor', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('date_sold', models.DateField(blank=True, null=True, verbose_name='Died')),
                ('po', models.CharField(max_length=20)),
                ('heat1', models.CharField(max_length=20)),
                ('heat2', models.CharField(max_length=20)),
                ('heat3', models.CharField(max_length=20)),
                ('heat4', models.CharField(max_length=20)),
                ('heat5', models.CharField(max_length=20)),
                ('udf2', models.CharField(max_length=20)),
                ('udf3', models.CharField(max_length=20)),
                ('status', models.CharField(blank=True, choices=[('f', 'Foreign'), ('d', 'Domestic')], default='d', help_text='Material Source', max_length=1)),
            ],
        ),
    ]
