# Generated by Django 2.0.3 on 2018-03-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='status',
            field=models.CharField(blank=True, choices=[('f', 'Foreign'), ('d', 'Domestic')], default='d', help_text='Source', max_length=1),
        ),
    ]
