# Generated by Django 2.0.3 on 2018-03-18 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180318_1741'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
