# Generated by Django 2.0.3 on 2018-03-18 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_delete_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='mill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Mill'),
        ),
    ]
