# Generated by Django 2.0.3 on 2018-03-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20180318_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='heat1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='heat2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='heat3',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='heat4',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='heat5',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='status',
            field=models.CharField(blank=True, choices=[('f', 'Foreign'), ('d', 'Domestic')], default='d', max_length=1),
        ),
        migrations.AlterField(
            model_name='material',
            name='udf2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='udf3',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
